#
# This GitHub action checks plugin repositories for valid docs.
#
# This provides a quick assessment on PRs of whether
# there might be issues with docs in plugin repositories.
#
# This is intended to help debug Vercel build issues, which
# may or may not be related to docs in plugin repositories.

name: "website: Check plugin docs"
on:
  pull_request:
    paths:
      - "website/**"
  schedule:
    - cron: "45 0 * * *"

jobs:
  check-plugin-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm i isomorphic-unfetch adm-zip gray-matter
      - name: Fetch and validate plugin docs
        run: node .github/workflows/check-plugin-docs.js
