#
# This GitHub action runs Packer go tests across
# Windows, Linux, and MacOS runners.
#

name: "Go Test"

on: [ workflow_dispatch, push ]

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  linux-go-tests:
    runs-on: ubuntu-latest
    name: Linux go tests
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: TESTARGS="-coverprofile=coverage.txt  -covermode=atomic" make ci
  darwin-go-tests:
    runs-on: macos-latest
    name: Darwin go tests
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go test ./... -coverprofile=coverage.txt  -covermode=atomic
  windows-go-tests:
    runs-on: windows-latest
    name: Windows go tests
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go test ./... -coverprofile=coverage.txt  -covermode=atomic
