on:
  schedule:
  - cron: "45 0 * * *"
name: Check Markdown links on main branch
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Set deployment URL env
      run:
        echo "DEPLOYMENT_URL=https://packer-git-master.hashicorp.vercel.app" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        file-extension: 'mdx'
        folder-path: 'website/content'
